In [2]:
# 查看当前挂载的数据集目录, 该目录下的变更重启环境后会自动还原
# View dataset directory. 
# This directory will be recovered automatically after resetting environment. 
!ls /home/aistudio/data

In [3]:
# 查看工作区文件, 该目录下的变更将会持久保存. 请及时清理不必要的文件, 避免加载过慢.
# View personal work directory. 
# All changes under this directory will be kept even after reset. 
# Please clean unnecessary files in time to speed up environment loading. 
!ls /home/aistudio/work

In [4]:
# 如果需要进行持久化安装, 需要使用持久化路径, 如下方代码示例:
# If a persistence installation is required, 
# you need to use the persistence path as the following: 
!mkdir /home/aistudio/external-libraries
!pip install beautifulsoup4 -t /home/aistudio/external-libraries

mkdir: 无法创建目录"/home/aistudio/external-libraries": 文件已存在
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9c/d8/909c4089dbe4ade9f9705f143c9f13f065049a9d5e7d34c828aefdd0a97c/beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/16/e3/4ad79882b92617e3a4a0df1960d6bce08edfb637737ac5c3f3ba29022e25/soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [4]:
# 同时添加如下代码, 这样每次环境(kernel)启动的时候只要运行下方代码即可: 
# Also add the following code, 
# so that every time the environment (kernel) starts, 
# just run the following code: 
import sys 
sys.path.append('/home/aistudio/external-libraries')

请点击[此处](https://ai.baidu.com/docs#/AIStudio_Project_Notebook/a38e5576)查看本环境基本用法.  <br>
Please click [here ](https://ai.baidu.com/docs#/AIStudio_Project_Notebook/a38e5576) for more detailed instructions. 

In [69]:
import pandas as pd
import numpy as py
datafile='/home/aistudio/data/titanic.csv'
f=pd.read_csv(datafile)
del f['Name']
del f['Ticket']
del f['Sex']
del f['Cabin']
del f['Embarked']
ceshi_data=f['Age'].dropna()
mean_age=ceshi_data.mean(axis=0)
#print(mean_age)
f['Age']=f['Age'].fillna(mean_age)
f_=py.array(f)
#print(f_)
maxx=f_.max(axis=0)
minn=f_.min(axis=0)
#print(maxx,end=',')
#print(minn,end=',')
avg=f_.mean(axis=0)
for i in range(len(f_[0])):
    f_[:,i]=(f_[:,i]-minn[i])/(maxx[i]-minn[i])
#list
ratio=0.80  #调节测试组数
offset=int(ratio*f.shape[0])
training_data=f_[:offset]
ceshi_data=f_[offset:]
training_data
x=training_data[:,:-1]
y=ceshi_data[:,:-1]
# 设置数学模型
w=[0.1,0.2,0.3,0.4,0.5,0.6]
w=py.array(w).reshape([6,1])
b=-0.2
#print(w)
W=w
class Network(object):
    # 随机化数学模型
    def __init__(self,num_of_weights):
        py.random.seed()
        self.w=py.random.randn(num_of_weights,1)
        print(self.w)
        W=self.w
        self.b=0.
    # 计算函数的预测值
    def forward(self,x):
        z=py.dot(x,self.w)+self.b
        return z
    # 计算函数的损失值
    def loss(self,z,y):
        error=z-y
        cost=error*error
        cost=py.mean(cost)
        return cost,W
        

net=Network(6)
x1=x[0:100]
y1=y[0:100]
z=net.forward(x1)
loss,W=net.loss(z,y1)
print(loss)
print(W)

[[-0.61956458]
 [-0.70662486]
 [-0.23477669]
 [-0.83997484]
 [-1.59888081]
 [-2.30599738]]
2.6970393626037708
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]]


In [216]:
A=[[ 1,  2,  3,  4,  5],
   [ 6,  7,  8,  9, 10],
   [11, 12, 13, 14, 15],
   [16, 17, 18, 19, 20]]
 
A = py.array(A)
print(A[:,:-1])
print(A[:,:4])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]
